### ISSUE TITLE
Pregledanje rada

### ISSUE THREAD

**Issue by jovanape** [MATF-RG17/RG133-christmas-tree#1]
Zavrsila sam projekat. Molim Vas pogledajte i recite ako nesto treba da popravim.
Hvala!

edit: Sada sam dodala i Makefile, ali izbacuje gresku kada njega koristim za prevodjenje. A ako samo napisem u terminalu:
gcc main.c functions.c texture.c loadmodel.c -o main -lGL -lGLU -lglut -lm
./main
prevodi se i pokrece bez problema.
Ako mozete samo to da pogledate u cemu je problem.
Hvala!

**Comment by ivan-cukic-matf** [comment]
U redu je Makefile (bar radi kod mene)
